# Generated by Django 4.0.1 on 2022-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='posts',
        ),
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(blank=True, to='forum.Post'),
        ),
    ]
