# Generated by Django 4.0.1 on 2022-04-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_topic_posts_topic_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='topic_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.topic'),
        ),
    ]
